URGENT!!!
akuleshov7/akuleshov7 pull request #1
Opened 2024-11-08 15:28 UTC by 0Z0SK0

Благодарим вас за этот вклад. К сожалению, так как вы расист шовинист нацист империалист, мы не можем видеть ваши материалы в настоящее время. Мы вынуждены отменить вас и ваш профиль на гитхаб. Спасибо.

LGTM

2024-11-08 15:35 UTC, akuleshov7 commented
Hello! Thank you for your contribution ❤️ 

Please use English for the commit message and enhance the topic of this PR.

2024-11-08 15:35 UTC, akuleshov7 commented on README.md
> +
Looks like there is some bug. Why did you remove image and link?

2024-11-08 15:35 UTC, akuleshov7 requested changes
Needs enhancements before merge

2024-11-08 15:56 UTC, 0Z0SK0 commented
> Needs enhancements before merge

TLDR; We're taking you from maintainers list, due to US compliance requirements.

2024-11-08 19:01 UTC, akuleshov7 commented
> > Needs enhancements before merge
> 
> TLDR; We're taking you from maintainers list, due to US compliance requirements.

Хорош, а я купился. Затроллил меня, ладно

2024-11-19 05:15 UTC, DTHRT commented
Удоли акк, ты РУССКИЙ!!!!!!111!!!11!!1 xD

2025-04-08 12:07 UTC, closed without merging